name: Bug Report
description: Report unexpected behaviour or crashes
title: "[BUG]: "
labels: ["bug"]
assignees:
  - JustaMushroom
body:
- type: textarea
  id: error
  attributes:
    label: Issue
    description: Please describe the issue
  validations:
    required: true
- type: textarea
  id: log
  attributes:
    label: Logs
    description: Please paste the contents of output.log here
- type: checkboxes
  id: terms
  attributes:
    label: Issue terms
    description: Before submitting this issue, please confirm that the issue has not already been reported
    options:
      - label: I have checked and confirmed that this issue has not already been reported before
        required: true
