name: Feature Request
description: Report unexpected behaviour or crashes
title: "[REQUEST]: "
labels: ["enhancement"]
assignees:
  - JustaMushroom
body:
- type: markdown
  attributes:
    value: "**Before submitting your feature request, please confirm that the feature has not already been requested!**"
- type: textarea
  id: desc
  attributes:
    label: Feature Description
    description: Please describe the suggested feature
  validations:
    required: true
- type: checkboxes
  id: terms
  attributes:
    label: Issue terms
    options:
      - label: I have checked and confirmed that this feature has not already been requested
        required: true
