# This is a basic workflow to help you get started with Actions

name: Auto-Assign

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  issues:
    types: [labeled]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  assign:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Assign to One Project
        uses: srggrs/assign-one-project-github-action@1.3.1
        if: |
          contains(github.event.issue.labels.*.name, 'bug')
          
        with:
          project: 'https://github.com/JustaMushroom/automatic-discord-game-searcher/projects/1'
          column_name: "Needs triage"

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Assign to One Project
        uses: srggrs/assign-one-project-github-action@1.3.1
        if: |
          contains(github.event.issue.labels.*.name, 'enhancement')
          
        with:
          project: 'https://github.com/JustaMushroom/automatic-discord-game-searcher/projects/2'
          column_name: "To do"
